In [ ]:
import numpy as np 

lista = [0.2,0.5,1.8,5.2,7.5]

some_array = np.array(object=lista)
print(some_array)

In [ ]:
#funzione che worka come range con(start,stop,step)

range_array = np.arange(1,50,4)
print(range_array)

[ 1  5  9 13 17 21 25 29 33 37 41 45 49]


In [ ]:
#reshape per creare una matrice 
 
nuovalist = [1,2,3,4,5,6,7,8,9,10,11,12]

nuovalist = np.reshape(nuovalist,shape=(4,3))

print(nuovalist)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
zero_array = np.zeros(shape=(10,20,30))

print(zero_array)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


In [6]:
np.unique(zero_array)

array([0.])

In [42]:
arraydip = np.arange(1,11)
np.array(object=arraydip)
print(arraydip,arraydip.ndim,arraydip.shape,arraydip.size,arraydip.dtype)
print(type(arraydip))

[ 1  2  3  4  5  6  7  8  9 10] 1 (10,) 10 int64
<class 'numpy.ndarray'>


In [45]:
#es 2

arzero = np.zeros(shape=(3,3),dtype=int)
print(arzero)
print("############")
arzero[1][1] = 5
print(arzero)


[[0 0 0]
 [0 0 0]
 [0 0 0]]
############
[[0 0 0]
 [0 5 0]
 [0 0 0]]


In [30]:
#es 3

arr1d = np.arange(2,21,2)

print(arr1d)


[ 2  4  6  8 10 12 14 16 18 20]


In [41]:
#es 4
arrfbf = np.random.randint(1,101,(4,4))

print(arrfbf[1:3,1:3])

[[51 31]
 [48  3]]


In [68]:
#es 5 

arrmltp = np.array([1,2,3])

multarr = arrmltp*2

forarr = np.array([4,5,6])

finalarr = np.concatenate((multarr,forarr))
finalarr.sort()
print(finalarr)





[2 4 4 5 6 6]


In [71]:
#somma di elementi
a = np.array([1,2,3])

b = a.sum()
print(b)

6


In [74]:
#media degli elementi

b = a.mean()
print(b)


2.0


In [76]:
#max e min
b = a.max()
c = a.min()

print(b,c)

3 1


In [77]:
#indice dell elemento max e min
b = a.argmax()
c = a.argmin()

print(b,c)

2 0


In [78]:
#confronto 

b = a > 2
print(b)

[False False  True]


In [79]:
#copia
b = a.copy()
print(b)


[1 2 3]


In [89]:
#ordinamento asse
b = np.sort(a)
print(b)
bidim_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
bidim_array.reshape(3,3)
print(bidim_array)
#per ordinare un array bidimensionale 
bidim_array.flatten() #torna l'array in una sola dimensione

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])